name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
            src: "./gColabNotebooks"
            version: 0.0.292
            args: --config pyproject.toml
      -  name: Run Ruff (lint)
         run: ruff check . --fix
      -  name: format
         run: ruff format .